max = 0
for s in [
    "minuit",
    "minuit",
    "minuit cinq",
    "minuit cinq",
    "minuit cinq",
    "minuit cinq",
    "minuit cinq",
    "minuit dix",
    "minuit dix",
    "minuit dix",
    "minuit dix",
    "minuit dix",
    "minuit et quart",
    "minuit et quart",
    "minuit et quart",
    "minuit et quart",
    "minuit et quart",
    "minuit vingt",
    "minuit vingt",
    "minuit vingt",
    "minuit vingt",
    "minuit vingt",
    "minuit vingt cinq",
    "minuit vingt cinq",
    "minuit vingt cinq",
    "minuit vingt cinq",
    "minuit vingt cinq",
    "minuit et demie",
    "minuit et demie",
    "minuit et demie",
    "minuit et demie",
    "minuit et demie",
    "une heure moins vingt cinq",
    "une heure moins vingt cinq",
    "une heure moins vingt cinq",
    "une heure moins vingt cinq",
    "une heure moins vingt cinq",
    "une heure moins vingt",
    "une heure moins vingt",
    "une heure moins vingt",
    "une heure moins vingt",
    "une heure moins vingt",
    "une heure moins le quart",
    "une heure moins le quart",
    "une heure moins le quart",
    "une heure moins le quart",
    "une heure moins le quart",
    "une heure moins dix",
    "une heure moins dix",
    "une heure moins dix",
    "une heure moins dix",
    "une heure moins dix",
    "une heure moins cinq",
    "une heure moins cinq",
    "une heure moins cinq",
    "une heure moins cinq",
    "une heure moins cinq",
    "une heure",
    "une heure",
    "une heure",
    "une heure",
    "une heure",
    "une heure cinq",
    "une heure cinq",
    "une heure cinq",
    "une heure cinq",
    "une heure cinq",
    "une heure dix",
    "une heure dix",
    "une heure dix",
    "une heure dix",
    "une heure dix",
    "une heure et quart",
    "une heure et quart",
    "une heure et quart",
    "une heure et quart",
    "une heure et quart",
    "une heure vingt",
    "une heure vingt",
    "une heure vingt",
    "une heure vingt",
    "une heure vingt",
    "une heure vingt cinq",
    "une heure vingt cinq",
    "une heure vingt cinq",
    "une heure vingt cinq",
    "une heure vingt cinq",
    "une heure et demie",
    "une heure et demie",
    "une heure et demie",
    "une heure et demie",
    "une heure et demie",
    "deux heures moins vingt cinq",
    "deux heures moins vingt cinq",
    "deux heures moins vingt cinq",
    "deux heures moins vingt cinq",
    "deux heures moins vingt cinq",
    "deux heures moins vingt",
    "deux heures moins vingt",
    "deux heures moins vingt",
    "deux heures moins vingt",
    "deux heures moins vingt",
    "deux heures moins le quart",
    "deux heures moins le quart",
    "deux heures moins le quart",
    "deux heures moins le quart",
    "deux heures moins le quart",
    "deux heures moins dix",
    "deux heures moins dix",
    "deux heures moins dix",
    "deux heures moins dix",
    "deux heures moins dix",
    "deux heures moins cinq",
    "deux heures moins cinq",
    "deux heures moins cinq",
    "deux heures moins cinq",
    "deux heures moins cinq",
    "deux heures",
    "deux heures",
    "deux heures",
    "deux heures",
    "deux heures",
    "deux heures cinq",
    "deux heures cinq",
    "deux heures cinq",
    "deux heures cinq",
    "deux heures cinq",
    "deux heures dix",
    "deux heures dix",
    "deux heures dix",
    "deux heures dix",
    "deux heures dix",
    "deux heures et quart",
    "deux heures et quart",
    "deux heures et quart",
    "deux heures et quart",
    "deux heures et quart",
    "deux heures vingt",
    "deux heures vingt",
    "deux heures vingt",
    "deux heures vingt",
    "deux heures vingt",
    "deux heures vingt cinq",
    "deux heures vingt cinq",
    "deux heures vingt cinq",
    "deux heures vingt cinq",
    "deux heures vingt cinq",
    "deux heures et demie",
    "deux heures et demie",
    "deux heures et demie",
    "deux heures et demie",
    "deux heures et demie",
    "trois heures moins vingt cinq",
    "trois heures moins vingt cinq",
    "trois heures moins vingt cinq",
    "trois heures moins vingt cinq",
    "trois heures moins vingt cinq",
    "trois heures moins vingt",
    "trois heures moins vingt",
    "trois heures moins vingt",
    "trois heures moins vingt",
    "trois heures moins vingt",
    "trois heures moins le quart",
    "trois heures moins le quart",
    "trois heures moins le quart",
    "trois heures moins le quart",
    "trois heures moins le quart",
    "trois heures moins dix",
    "trois heures moins dix",
    "trois heures moins dix",
    "trois heures moins dix",
    "trois heures moins dix",
    "trois heures moins cinq",
    "trois heures moins cinq",
    "trois heures moins cinq",
    "trois heures moins cinq",
    "trois heures moins cinq",
    "trois heures",
    "trois heures",
    "trois heures",
    "trois heures",
    "trois heures",
    "trois heures cinq",
    "trois heures cinq",
    "trois heures cinq",
    "trois heures cinq",
    "trois heures cinq",
    "trois heures dix",
    "trois heures dix",
    "trois heures dix",
    "trois heures dix",
    "trois heures dix",
    "trois heures et quart",
    "trois heures et quart",
    "trois heures et quart",
    "trois heures et quart",
    "trois heures et quart",
    "trois heures vingt",
    "trois heures vingt",
    "trois heures vingt",
    "trois heures vingt",
    "trois heures vingt",
    "trois heures vingt cinq",
    "trois heures vingt cinq",
    "trois heures vingt cinq",
    "trois heures vingt cinq",
    "trois heures vingt cinq",
    "trois heures et demie",
    "trois heures et demie",
    "trois heures et demie",
    "trois heures et demie",
    "trois heures et demie",
    "quatre heures moins vingt cinq",
    "quatre heures moins vingt cinq",
    "quatre heures moins vingt cinq",
    "quatre heures moins vingt cinq",
    "quatre heures moins vingt cinq",
    "quatre heures moins vingt",
    "quatre heures moins vingt",
    "quatre heures moins vingt",
    "quatre heures moins vingt",
    "quatre heures moins vingt",
    "quatre heures moins le quart",
    "quatre heures moins le quart",
    "quatre heures moins le quart",
    "quatre heures moins le quart",
    "quatre heures moins le quart",
    "quatre heures moins dix",
    "quatre heures moins dix",
    "quatre heures moins dix",
    "quatre heures moins dix",
    "quatre heures moins dix",
    "quatre heures moins cinq",
    "quatre heures moins cinq",
    "quatre heures moins cinq",
    "quatre heures moins cinq",
    "quatre heures moins cinq",
    "quatre heures",
    "quatre heures",
    "quatre heures",
    "quatre heures",
    "quatre heures",
    "quatre heures cinq",
    "quatre heures cinq",
    "quatre heures cinq",
    "quatre heures cinq",
    "quatre heures cinq",
    "quatre heures dix",
    "quatre heures dix",
    "quatre heures dix",
    "quatre heures dix",
    "quatre heures dix",
    "quatre heures et quart",
    "quatre heures et quart",
    "quatre heures et quart",
    "quatre heures et quart",
    "quatre heures et quart",
    "quatre heures vingt",
    "quatre heures vingt",
    "quatre heures vingt",
    "quatre heures vingt",
    "quatre heures vingt",
    "quatre heures vingt cinq",
    "quatre heures vingt cinq",
    "quatre heures vingt cinq",
    "quatre heures vingt cinq",
    "quatre heures vingt cinq",
    "quatre heures et demie",
    "quatre heures et demie",
    "quatre heures et demie",
    "quatre heures et demie",
    "quatre heures et demie",
    "cinq heures moins vingt cinq",
    "cinq heures moins vingt cinq",
    "cinq heures moins vingt cinq",
    "cinq heures moins vingt cinq",
    "cinq heures moins vingt cinq",
    "cinq heures moins vingt",
    "cinq heures moins vingt",
    "cinq heures moins vingt",
    "cinq heures moins vingt",
    "cinq heures moins vingt",
    "cinq heures moins le quart",
    "cinq heures moins le quart",
    "cinq heures moins le quart",
    "cinq heures moins le quart",
    "cinq heures moins le quart",
    "cinq heures moins dix",
    "cinq heures moins dix",
    "cinq heures moins dix",
    "cinq heures moins dix",
    "cinq heures moins dix",
    "cinq heures moins cinq",
    "cinq heures moins cinq",
    "cinq heures moins cinq",
    "cinq heures moins cinq",
    "cinq heures moins cinq",
    "cinq heures",
    "cinq heures",
    "cinq heures",
    "cinq heures",
    "cinq heures",
    "cinq heures cinq",
    "cinq heures cinq",
    "cinq heures cinq",
    "cinq heures cinq",
    "cinq heures cinq",
    "cinq heures dix",
    "cinq heures dix",
    "cinq heures dix",
    "cinq heures dix",
    "cinq heures dix",
    "cinq heures et quart",
    "cinq heures et quart",
    "cinq heures et quart",
    "cinq heures et quart",
    "cinq heures et quart",
    "cinq heures vingt",
    "cinq heures vingt",
    "cinq heures vingt",
    "cinq heures vingt",
    "cinq heures vingt",
    "cinq heures vingt cinq",
    "cinq heures vingt cinq",
    "cinq heures vingt cinq",
    "cinq heures vingt cinq",
    "cinq heures vingt cinq",
    "cinq heures et demie",
    "cinq heures et demie",
    "cinq heures et demie",
    "cinq heures et demie",
    "cinq heures et demie",
    "six heures moins vingt cinq",
    "six heures moins vingt cinq",
    "six heures moins vingt cinq",
    "six heures moins vingt cinq",
    "six heures moins vingt cinq",
    "six heures moins vingt",
    "six heures moins vingt",
    "six heures moins vingt",
    "six heures moins vingt",
    "six heures moins vingt",
    "six heures moins le quart",
    "six heures moins le quart",
    "six heures moins le quart",
    "six heures moins le quart",
    "six heures moins le quart",
    "six heures moins dix",
    "six heures moins dix",
    "six heures moins dix",
    "six heures moins dix",
    "six heures moins dix",
    "six heures moins cinq",
    "six heures moins cinq",
    "six heures moins cinq",
    "six heures moins cinq",
    "six heures moins cinq",
    "six heures",
    "six heures",
    "six heures",
    "six heures",
    "six heures",
    "six heures cinq",
    "six heures cinq",
    "six heures cinq",
    "six heures cinq",
    "six heures cinq",
    "six heures dix",
    "six heures dix",
    "six heures dix",
    "six heures dix",
    "six heures dix",
    "six heures et quart",
    "six heures et quart",
    "six heures et quart",
    "six heures et quart",
    "six heures et quart",
    "six heures vingt",
    "six heures vingt",
    "six heures vingt",
    "six heures vingt",
    "six heures vingt",
    "six heures vingt cinq",
    "six heures vingt cinq",
    "six heures vingt cinq",
    "six heures vingt cinq",
    "six heures vingt cinq",
    "six heures et demie",
    "six heures et demie",
    "six heures et demie",
    "six heures et demie",
    "six heures et demie",
    "sept heures moins vingt cinq",
    "sept heures moins vingt cinq",
    "sept heures moins vingt cinq",
    "sept heures moins vingt cinq",
    "sept heures moins vingt cinq",
    "sept heures moins vingt",
    "sept heures moins vingt",
    "sept heures moins vingt",
    "sept heures moins vingt",
    "sept heures moins vingt",
    "sept heures moins le quart",
    "sept heures moins le quart",
    "sept heures moins le quart",
    "sept heures moins le quart",
    "sept heures moins le quart",
    "sept heures moins dix",
    "sept heures moins dix",
    "sept heures moins dix",
    "sept heures moins dix",
    "sept heures moins dix",
    "sept heures moins cinq",
    "sept heures moins cinq",
    "sept heures moins cinq",
    "sept heures moins cinq",
    "sept heures moins cinq",
    "sept heures",
    "sept heures",
    "sept heures",
    "sept heures",
    "sept heures",
    "sept heures cinq",
    "sept heures cinq",
    "sept heures cinq",
    "sept heures cinq",
    "sept heures cinq",
    "sept heures dix",
    "sept heures dix",
    "sept heures dix",
    "sept heures dix",
    "sept heures dix",
    "sept heures et quart",
    "sept heures et quart",
    "sept heures et quart",
    "sept heures et quart",
    "sept heures et quart",
    "sept heures vingt",
    "sept heures vingt",
    "sept heures vingt",
    "sept heures vingt",
    "sept heures vingt",
    "sept heures vingt cinq",
    "sept heures vingt cinq",
    "sept heures vingt cinq",
    "sept heures vingt cinq",
    "sept heures vingt cinq",
    "sept heures et demie",
    "sept heures et demie",
    "sept heures et demie",
    "sept heures et demie",
    "sept heures et demie",
    "huit heures moins vingt cinq",
    "huit heures moins vingt cinq",
    "huit heures moins vingt cinq",
    "huit heures moins vingt cinq",
    "huit heures moins vingt cinq",
    "huit heures moins vingt",
    "huit heures moins vingt",
    "huit heures moins vingt",
    "huit heures moins vingt",
    "huit heures moins vingt",
    "huit heures moins le quart",
    "huit heures moins le quart",
    "huit heures moins le quart",
    "huit heures moins le quart",
    "huit heures moins le quart",
    "huit heures moins dix",
    "huit heures moins dix",
    "huit heures moins dix",
    "huit heures moins dix",
    "huit heures moins dix",
    "huit heures moins cinq",
    "huit heures moins cinq",
    "huit heures moins cinq",
    "huit heures moins cinq",
    "huit heures moins cinq",
    "huit heures",
    "huit heures",
    "huit heures",
    "huit heures",
    "huit heures",
    "huit heures cinq",
    "huit heures cinq",
    "huit heures cinq",
    "huit heures cinq",
    "huit heures cinq",
    "huit heures dix",
    "huit heures dix",
    "huit heures dix",
    "huit heures dix",
    "huit heures dix",
    "huit heures et quart",
    "huit heures et quart",
    "huit heures et quart",
    "huit heures et quart",
    "huit heures et quart",
    "huit heures vingt",
    "huit heures vingt",
    "huit heures vingt",
    "huit heures vingt",
    "huit heures vingt",
    "huit heures vingt cinq",
    "huit heures vingt cinq",
    "huit heures vingt cinq",
    "huit heures vingt cinq",
    "huit heures vingt cinq",
    "huit heures et demie",
    "huit heures et demie",
    "huit heures et demie",
    "huit heures et demie",
    "huit heures et demie",
    "neuf heures moins vingt cinq",
    "neuf heures moins vingt cinq",
    "neuf heures moins vingt cinq",
    "neuf heures moins vingt cinq",
    "neuf heures moins vingt cinq",
    "neuf heures moins vingt",
    "neuf heures moins vingt",
    "neuf heures moins vingt",
    "neuf heures moins vingt",
    "neuf heures moins vingt",
    "neuf heures moins le quart",
    "neuf heures moins le quart",
    "neuf heures moins le quart",
    "neuf heures moins le quart",
    "neuf heures moins le quart",
    "neuf heures moins dix",
    "neuf heures moins dix",
    "neuf heures moins dix",
    "neuf heures moins dix",
    "neuf heures moins dix",
    "neuf heures moins cinq",
    "neuf heures moins cinq",
    "neuf heures moins cinq",
    "neuf heures moins cinq",
    "neuf heures moins cinq",
    "neuf heures",
    "neuf heures",
    "neuf heures",
    "neuf heures",
    "neuf heures",
    "neuf heures cinq",
    "neuf heures cinq",
    "neuf heures cinq",
    "neuf heures cinq",
    "neuf heures cinq",
    "neuf heures dix",
    "neuf heures dix",
    "neuf heures dix",
    "neuf heures dix",
    "neuf heures dix",
    "neuf heures et quart",
    "neuf heures et quart",
    "neuf heures et quart",
    "neuf heures et quart",
    "neuf heures et quart",
    "neuf heures vingt",
    "neuf heures vingt",
    "neuf heures vingt",
    "neuf heures vingt",
    "neuf heures vingt",
    "neuf heures vingt cinq",
    "neuf heures vingt cinq",
    "neuf heures vingt cinq",
    "neuf heures vingt cinq",
    "neuf heures vingt cinq",
    "neuf heures et demie",
    "neuf heures et demie",
    "neuf heures et demie",
    "neuf heures et demie",
    "neuf heures et demie",
    "dix heures moins vingt cinq",
    "dix heures moins vingt cinq",
    "dix heures moins vingt cinq",
    "dix heures moins vingt cinq",
    "dix heures moins vingt cinq",
    "dix heures moins vingt",
    "dix heures moins vingt",
    "dix heures moins vingt",
    "dix heures moins vingt",
    "dix heures moins vingt",
    "dix heures moins le quart",
    "dix heures moins le quart",
    "dix heures moins le quart",
    "dix heures moins le quart",
    "dix heures moins le quart",
    "dix heures moins dix",
    "dix heures moins dix",
    "dix heures moins dix",
    "dix heures moins dix",
    "dix heures moins dix",
    "dix heures moins cinq",
    "dix heures moins cinq",
    "dix heures moins cinq",
    "dix heures moins cinq",
    "dix heures moins cinq",
    "dix heures",
    "dix heures",
    "dix heures",
    "dix heures",
    "dix heures",
    "dix heures cinq",
    "dix heures cinq",
    "dix heures cinq",
    "dix heures cinq",
    "dix heures cinq",
    "dix heures dix",
    "dix heures dix",
    "dix heures dix",
    "dix heures dix",
    "dix heures dix",
    "dix heures et quart",
    "dix heures et quart",
    "dix heures et quart",
    "dix heures et quart",
    "dix heures et quart",
    "dix heures vingt",
    "dix heures vingt",
    "dix heures vingt",
    "dix heures vingt",
    "dix heures vingt",
    "dix heures vingt cinq",
    "dix heures vingt cinq",
    "dix heures vingt cinq",
    "dix heures vingt cinq",
    "dix heures vingt cinq",
    "dix heures et demie",
    "dix heures et demie",
    "dix heures et demie",
    "dix heures et demie",
    "dix heures et demie",
    "onze heures moins vingt cinq",
    "onze heures moins vingt cinq",
    "onze heures moins vingt cinq",
    "onze heures moins vingt cinq",
    "onze heures moins vingt cinq",
    "onze heures moins vingt",
    "onze heures moins vingt",
    "onze heures moins vingt",
    "onze heures moins vingt",
    "onze heures moins vingt",
    "onze heures moins le quart",
    "onze heures moins le quart",
    "onze heures moins le quart",
    "onze heures moins le quart",
    "onze heures moins le quart",
    "onze heures moins dix",
    "onze heures moins dix",
    "onze heures moins dix",
    "onze heures moins dix",
    "onze heures moins dix",
    "onze heures moins cinq",
    "onze heures moins cinq",
    "onze heures moins cinq",
    "onze heures moins cinq",
    "onze heures moins cinq",
    "onze heures",
    "onze heures",
    "onze heures",
    "onze heures",
    "onze heures",
    "onze heures cinq",
    "onze heures cinq",
    "onze heures cinq",
    "onze heures cinq",
    "onze heures cinq",
    "onze heures dix",
    "onze heures dix",
    "onze heures dix",
    "onze heures dix",
    "onze heures dix",
    "onze heures et quart",
    "onze heures et quart",
    "onze heures et quart",
    "onze heures et quart",
    "onze heures et quart",
    "onze heures vingt",
    "onze heures vingt",
    "onze heures vingt",
    "onze heures vingt",
    "onze heures vingt",
    "onze heures vingt cinq",
    "onze heures vingt cinq",
    "onze heures vingt cinq",
    "onze heures vingt cinq",
    "onze heures vingt cinq",
    "onze heures et demie",
    "onze heures et demie",
    "onze heures et demie",
    "onze heures et demie",
    "onze heures et demie",
    "midi moins vingt cinq",
    "midi moins vingt cinq",
    "midi moins vingt cinq",
    "midi moins vingt cinq",
    "midi moins vingt cinq",
    "midi moins vingt",
    "midi moins vingt",
    "midi moins vingt",
    "midi moins vingt",
    "midi moins vingt",
    "midi moins le quart",
    "midi moins le quart",
    "midi moins le quart",
    "midi moins le quart",
    "midi moins le quart",
    "midi moins dix",
    "midi moins dix",
    "midi moins dix",
    "midi moins dix",
    "midi moins dix",
    "midi moins cinq",
    "midi moins cinq",
    "midi moins cinq",
    "midi moins cinq",
    "midi moins cinq",
    "midi",
    "midi",
    "midi",
    "midi",
    "midi",
    "midi cinq",
    "midi cinq",
    "midi cinq",
    "midi cinq",
    "midi cinq",
    "midi dix",
    "midi dix",
    "midi dix",
    "midi dix",
    "midi dix",
    "midi et quart",
    "midi et quart",
    "midi et quart",
    "midi et quart",
    "midi et quart",
    "midi vingt",
    "midi vingt",
    "midi vingt",
    "midi vingt",
    "midi vingt",
    "midi vingt cinq",
    "midi vingt cinq",
    "midi vingt cinq",
    "midi vingt cinq",
    "midi vingt cinq",
    "midi et demie",
    "midi et demie",
    "midi et demie",
    "midi et demie",
    "midi et demie",
    "une heures moins vingt cinq",
    "une heures moins vingt cinq",
    "une heures moins vingt cinq",
    "une heures moins vingt cinq",
    "une heures moins vingt cinq",
    "une heures moins vingt",
    "une heures moins vingt",
    "une heures moins vingt",
    "une heures moins vingt",
    "une heures moins vingt",
    "une heures moins le quart",
    "une heures moins le quart",
    "une heures moins le quart",
    "une heures moins le quart",
    "une heures moins le quart",
    "une heures moins dix",
    "une heures moins dix",
    "une heures moins dix",
    "une heures moins dix",
    "une heures moins dix",
    "une heures moins cinq",
    "une heures moins cinq",
    "une heures moins cinq",
    "une heures moins cinq",
    "une heures moins cinq",
    "une heures",
    "une heures",
    "une heures",
    "une heures",
    "une heures",
    "une heures cinq",
    "une heures cinq",
    "une heures cinq",
    "une heures cinq",
    "une heures cinq",
    "une heures dix",
    "une heures dix",
    "une heures dix",
    "une heures dix",
    "une heures dix",
    "une heures et quart",
    "une heures et quart",
    "une heures et quart",
    "une heures et quart",
    "une heures et quart",
    "une heures vingt",
    "une heures vingt",
    "une heures vingt",
    "une heures vingt",
    "une heures vingt",
    "une heures vingt cinq",
    "une heures vingt cinq",
    "une heures vingt cinq",
    "une heures vingt cinq",
    "une heures vingt cinq",
    "une heures et demie",
    "une heures et demie",
    "une heures et demie",
    "une heures et demie",
    "une heures et demie",
    "deux heures moins vingt cinq",
    "deux heures moins vingt cinq",
    "deux heures moins vingt cinq",
    "deux heures moins vingt cinq",
    "deux heures moins vingt cinq",
    "deux heures moins vingt",
    "deux heures moins vingt",
    "deux heures moins vingt",
    "deux heures moins vingt",
    "deux heures moins vingt",
    "deux heures moins le quart",
    "deux heures moins le quart",
    "deux heures moins le quart",
    "deux heures moins le quart",
    "deux heures moins le quart",
    "deux heures moins dix",
    "deux heures moins dix",
    "deux heures moins dix",
    "deux heures moins dix",
    "deux heures moins dix",
    "deux heures moins cinq",
    "deux heures moins cinq",
    "deux heures moins cinq",
    "deux heures moins cinq",
    "deux heures moins cinq",
    "deux heures",
    "deux heures",
    "deux heures",
    "deux heures",
    "deux heures",
    "deux heures cinq",
    "deux heures cinq",
    "deux heures cinq",
    "deux heures cinq",
    "deux heures cinq",
    "deux heures dix",
    "deux heures dix",
    "deux heures dix",
    "deux heures dix",
    "deux heures dix",
    "deux heures et quart",
    "deux heures et quart",
    "deux heures et quart",
    "deux heures et quart",
    "deux heures et quart",
    "deux heures vingt",
    "deux heures vingt",
    "deux heures vingt",
    "deux heures vingt",
    "deux heures vingt",
    "deux heures vingt cinq",
    "deux heures vingt cinq",
    "deux heures vingt cinq",
    "deux heures vingt cinq",
    "deux heures vingt cinq",
    "deux heures et demie",
    "deux heures et demie",
    "deux heures et demie",
    "deux heures et demie",
    "deux heures et demie",
    "trois heures moins vingt cinq",
    "trois heures moins vingt cinq",
    "trois heures moins vingt cinq",
    "trois heures moins vingt cinq",
    "trois heures moins vingt cinq",
    "trois heures moins vingt",
    "trois heures moins vingt",
    "trois heures moins vingt",
    "trois heures moins vingt",
    "trois heures moins vingt",
    "trois heures moins le quart",
    "trois heures moins le quart",
    "trois heures moins le quart",
    "trois heures moins le quart",
    "trois heures moins le quart",
    "trois heures moins dix",
    "trois heures moins dix",
    "trois heures moins dix",
    "trois heures moins dix",
    "trois heures moins dix",
    "trois heures moins cinq",
    "trois heures moins cinq",
    "trois heures moins cinq",
    "trois heures moins cinq",
    "trois heures moins cinq",
    "trois heures",
    "trois heures",
    "trois heures",
    "trois heures",
    "trois heures",
    "trois heures cinq",
    "trois heures cinq",
    "trois heures cinq",
    "trois heures cinq",
    "trois heures cinq",
    "trois heures dix",
    "trois heures dix",
    "trois heures dix",
    "trois heures dix",
    "trois heures dix",
    "trois heures et quart",
    "trois heures et quart",
    "trois heures et quart",
    "trois heures et quart",
    "trois heures et quart",
    "trois heures vingt",
    "trois heures vingt",
    "trois heures vingt",
    "trois heures vingt",
    "trois heures vingt",
    "trois heures vingt cinq",
    "trois heures vingt cinq",
    "trois heures vingt cinq",
    "trois heures vingt cinq",
    "trois heures vingt cinq",
    "trois heures et demie",
    "trois heures et demie",
    "trois heures et demie",
    "trois heures et demie",
    "trois heures et demie",
    "quatre heures moins vingt cinq",
    "quatre heures moins vingt cinq",
    "quatre heures moins vingt cinq",
    "quatre heures moins vingt cinq",
    "quatre heures moins vingt cinq",
    "quatre heures moins vingt",
    "quatre heures moins vingt",
    "quatre heures moins vingt",
    "quatre heures moins vingt",
    "quatre heures moins vingt",
    "quatre heures moins le quart",
    "quatre heures moins le quart",
    "quatre heures moins le quart",
    "quatre heures moins le quart",
    "quatre heures moins le quart",
    "quatre heures moins dix",
    "quatre heures moins dix",
    "quatre heures moins dix",
    "quatre heures moins dix",
    "quatre heures moins dix",
    "quatre heures moins cinq",
    "quatre heures moins cinq",
    "quatre heures moins cinq",
    "quatre heures moins cinq",
    "quatre heures moins cinq",
    "quatre heures",
    "quatre heures",
    "quatre heures",
    "quatre heures",
    "quatre heures",
    "quatre heures cinq",
    "quatre heures cinq",
    "quatre heures cinq",
    "quatre heures cinq",
    "quatre heures cinq",
    "quatre heures dix",
    "quatre heures dix",
    "quatre heures dix",
    "quatre heures dix",
    "quatre heures dix",
    "quatre heures et quart",
    "quatre heures et quart",
    "quatre heures et quart",
    "quatre heures et quart",
    "quatre heures et quart",
    "quatre heures vingt",
    "quatre heures vingt",
    "quatre heures vingt",
    "quatre heures vingt",
    "quatre heures vingt",
    "quatre heures vingt cinq",
    "quatre heures vingt cinq",
    "quatre heures vingt cinq",
    "quatre heures vingt cinq",
    "quatre heures vingt cinq",
    "quatre heures et demie",
    "quatre heures et demie",
    "quatre heures et demie",
    "quatre heures et demie",
    "quatre heures et demie",
    "cinq heures moins vingt cinq",
    "cinq heures moins vingt cinq",
    "cinq heures moins vingt cinq",
    "cinq heures moins vingt cinq",
    "cinq heures moins vingt cinq",
    "cinq heures moins vingt",
    "cinq heures moins vingt",
    "cinq heures moins vingt",
    "cinq heures moins vingt",
    "cinq heures moins vingt",
    "cinq heures moins le quart",
    "cinq heures moins le quart",
    "cinq heures moins le quart",
    "cinq heures moins le quart",
    "cinq heures moins le quart",
    "cinq heures moins dix",
    "cinq heures moins dix",
    "cinq heures moins dix",
    "cinq heures moins dix",
    "cinq heures moins dix",
    "cinq heures moins cinq",
    "cinq heures moins cinq",
    "cinq heures moins cinq",
    "cinq heures moins cinq",
    "cinq heures moins cinq",
    "cinq heures",
    "cinq heures",
    "cinq heures",
    "cinq heures",
    "cinq heures",
    "cinq heures cinq",
    "cinq heures cinq",
    "cinq heures cinq",
    "cinq heures cinq",
    "cinq heures cinq",
    "cinq heures dix",
    "cinq heures dix",
    "cinq heures dix",
    "cinq heures dix",
    "cinq heures dix",
    "cinq heures et quart",
    "cinq heures et quart",
    "cinq heures et quart",
    "cinq heures et quart",
    "cinq heures et quart",
    "cinq heures vingt",
    "cinq heures vingt",
    "cinq heures vingt",
    "cinq heures vingt",
    "cinq heures vingt",
    "cinq heures vingt cinq",
    "cinq heures vingt cinq",
    "cinq heures vingt cinq",
    "cinq heures vingt cinq",
    "cinq heures vingt cinq",
    "cinq heures et demie",
    "cinq heures et demie",
    "cinq heures et demie",
    "cinq heures et demie",
    "cinq heures et demie",
    "six heures moins vingt cinq",
    "six heures moins vingt cinq",
    "six heures moins vingt cinq",
    "six heures moins vingt cinq",
    "six heures moins vingt cinq",
    "six heures moins vingt",
    "six heures moins vingt",
    "six heures moins vingt",
    "six heures moins vingt",
    "six heures moins vingt",
    "six heures moins le quart",
    "six heures moins le quart",
    "six heures moins le quart",
    "six heures moins le quart",
    "six heures moins le quart",
    "six heures moins dix",
    "six heures moins dix",
    "six heures moins dix",
    "six heures moins dix",
    "six heures moins dix",
    "six heures moins cinq",
    "six heures moins cinq",
    "six heures moins cinq",
    "six heures moins cinq",
    "six heures moins cinq",
    "six heures",
    "six heures",
    "six heures",
    "six heures",
    "six heures",
    "six heures cinq",
    "six heures cinq",
    "six heures cinq",
    "six heures cinq",
    "six heures cinq",
    "six heures dix",
    "six heures dix",
    "six heures dix",
    "six heures dix",
    "six heures dix",
    "six heures et quart",
    "six heures et quart",
    "six heures et quart",
    "six heures et quart",
    "six heures et quart",
    "six heures vingt",
    "six heures vingt",
    "six heures vingt",
    "six heures vingt",
    "six heures vingt",
    "six heures vingt cinq",
    "six heures vingt cinq",
    "six heures vingt cinq",
    "six heures vingt cinq",
    "six heures vingt cinq",
    "six heures et demie",
    "six heures et demie",
    "six heures et demie",
    "six heures et demie",
    "six heures et demie",
    "sept heures moins vingt cinq",
    "sept heures moins vingt cinq",
    "sept heures moins vingt cinq",
    "sept heures moins vingt cinq",
    "sept heures moins vingt cinq",
    "sept heures moins vingt",
    "sept heures moins vingt",
    "sept heures moins vingt",
    "sept heures moins vingt",
    "sept heures moins vingt",
    "sept heures moins le quart",
    "sept heures moins le quart",
    "sept heures moins le quart",
    "sept heures moins le quart",
    "sept heures moins le quart",
    "sept heures moins dix",
    "sept heures moins dix",
    "sept heures moins dix",
    "sept heures moins dix",
    "sept heures moins dix",
    "sept heures moins cinq",
    "sept heures moins cinq",
    "sept heures moins cinq",
    "sept heures moins cinq",
    "sept heures moins cinq",
    "sept heures",
    "sept heures",
    "sept heures",
    "sept heures",
    "sept heures",
    "sept heures cinq",
    "sept heures cinq",
    "sept heures cinq",
    "sept heures cinq",
    "sept heures cinq",
    "sept heures dix",
    "sept heures dix",
    "sept heures dix",
    "sept heures dix",
    "sept heures dix",
    "sept heures et quart",
    "sept heures et quart",
    "sept heures et quart",
    "sept heures et quart",
    "sept heures et quart",
    "sept heures vingt",
    "sept heures vingt",
    "sept heures vingt",
    "sept heures vingt",
    "sept heures vingt",
    "sept heures vingt cinq",
    "sept heures vingt cinq",
    "sept heures vingt cinq",
    "sept heures vingt cinq",
    "sept heures vingt cinq",
    "sept heures et demie",
    "sept heures et demie",
    "sept heures et demie",
    "sept heures et demie",
    "sept heures et demie",
    "huit heures moins vingt cinq",
    "huit heures moins vingt cinq",
    "huit heures moins vingt cinq",
    "huit heures moins vingt cinq",
    "huit heures moins vingt cinq",
    "huit heures moins vingt",
    "huit heures moins vingt",
    "huit heures moins vingt",
    "huit heures moins vingt",
    "huit heures moins vingt",
    "huit heures moins le quart",
    "huit heures moins le quart",
    "huit heures moins le quart",
    "huit heures moins le quart",
    "huit heures moins le quart",
    "huit heures moins dix",
    "huit heures moins dix",
    "huit heures moins dix",
    "huit heures moins dix",
    "huit heures moins dix",
    "huit heures moins cinq",
    "huit heures moins cinq",
    "huit heures moins cinq",
    "huit heures moins cinq",
    "huit heures moins cinq",
    "huit heures",
    "huit heures",
    "huit heures",
    "huit heures",
    "huit heures",
    "huit heures cinq",
    "huit heures cinq",
    "huit heures cinq",
    "huit heures cinq",
    "huit heures cinq",
    "huit heures dix",
    "huit heures dix",
    "huit heures dix",
    "huit heures dix",
    "huit heures dix",
    "huit heures et quart",
    "huit heures et quart",
    "huit heures et quart",
    "huit heures et quart",
    "huit heures et quart",
    "huit heures vingt",
    "huit heures vingt",
    "huit heures vingt",
    "huit heures vingt",
    "huit heures vingt",
    "huit heures vingt cinq",
    "huit heures vingt cinq",
    "huit heures vingt cinq",
    "huit heures vingt cinq",
    "huit heures vingt cinq",
    "huit heures et demie",
    "huit heures et demie",
    "huit heures et demie",
    "huit heures et demie",
    "huit heures et demie",
    "neuf heures moins vingt cinq",
    "neuf heures moins vingt cinq",
    "neuf heures moins vingt cinq",
    "neuf heures moins vingt cinq",
    "neuf heures moins vingt cinq",
    "neuf heures moins vingt",
    "neuf heures moins vingt",
    "neuf heures moins vingt",
    "neuf heures moins vingt",
    "neuf heures moins vingt",
    "neuf heures moins le quart",
    "neuf heures moins le quart",
    "neuf heures moins le quart",
    "neuf heures moins le quart",
    "neuf heures moins le quart",
    "neuf heures moins dix",
    "neuf heures moins dix",
    "neuf heures moins dix",
    "neuf heures moins dix",
    "neuf heures moins dix",
    "neuf heures moins cinq",
    "neuf heures moins cinq",
    "neuf heures moins cinq",
    "neuf heures moins cinq",
    "neuf heures moins cinq",
    "neuf heures",
    "neuf heures",
    "neuf heures",
    "neuf heures",
    "neuf heures",
    "neuf heures cinq",
    "neuf heures cinq",
    "neuf heures cinq",
    "neuf heures cinq",
    "neuf heures cinq",
    "neuf heures dix",
    "neuf heures dix",
    "neuf heures dix",
    "neuf heures dix",
    "neuf heures dix",
    "neuf heures et quart",
    "neuf heures et quart",
    "neuf heures et quart",
    "neuf heures et quart",
    "neuf heures et quart",
    "neuf heures vingt",
    "neuf heures vingt",
    "neuf heures vingt",
    "neuf heures vingt",
    "neuf heures vingt",
    "neuf heures vingt cinq",
    "neuf heures vingt cinq",
    "neuf heures vingt cinq",
    "neuf heures vingt cinq",
    "neuf heures vingt cinq",
    "neuf heures et demie",
    "neuf heures et demie",
    "neuf heures et demie",
    "neuf heures et demie",
    "neuf heures et demie",
    "dix heures moins vingt cinq",
    "dix heures moins vingt cinq",
    "dix heures moins vingt cinq",
    "dix heures moins vingt cinq",
    "dix heures moins vingt cinq",
    "dix heures moins vingt",
    "dix heures moins vingt",
    "dix heures moins vingt",
    "dix heures moins vingt",
    "dix heures moins vingt",
    "dix heures moins le quart",
    "dix heures moins le quart",
    "dix heures moins le quart",
    "dix heures moins le quart",
    "dix heures moins le quart",
    "dix heures moins dix",
    "dix heures moins dix",
    "dix heures moins dix",
    "dix heures moins dix",
    "dix heures moins dix",
    "dix heures moins cinq",
    "dix heures moins cinq",
    "dix heures moins cinq",
    "dix heures moins cinq",
    "dix heures moins cinq",
    "dix heures",
    "dix heures",
    "dix heures",
    "dix heures",
    "dix heures",
    "dix heures cinq",
    "dix heures cinq",
    "dix heures cinq",
    "dix heures cinq",
    "dix heures cinq",
    "dix heures dix",
    "dix heures dix",
    "dix heures dix",
    "dix heures dix",
    "dix heures dix",
    "dix heures et quart",
    "dix heures et quart",
    "dix heures et quart",
    "dix heures et quart",
    "dix heures et quart",
    "dix heures vingt",
    "dix heures vingt",
    "dix heures vingt",
    "dix heures vingt",
    "dix heures vingt",
    "dix heures vingt cinq",
    "dix heures vingt cinq",
    "dix heures vingt cinq",
    "dix heures vingt cinq",
    "dix heures vingt cinq",
    "dix heures et demie",
    "dix heures et demie",
    "dix heures et demie",
    "dix heures et demie",
    "dix heures et demie",
    "onze heures moins vingt cinq",
    "onze heures moins vingt cinq",
    "onze heures moins vingt cinq",
    "onze heures moins vingt cinq",
    "onze heures moins vingt cinq",
    "onze heures moins vingt",
    "onze heures moins vingt",
    "onze heures moins vingt",
    "onze heures moins vingt",
    "onze heures moins vingt",
    "onze heures moins le quart",
    "onze heures moins le quart",
    "onze heures moins le quart",
    "onze heures moins le quart",
    "onze heures moins le quart",
    "onze heures moins dix",
    "onze heures moins dix",
    "onze heures moins dix",
    "onze heures moins dix",
    "onze heures moins dix",
    "onze heures moins cinq",
    "onze heures moins cinq",
    "onze heures moins cinq",
    "onze heures moins cinq",
    "onze heures moins cinq",
    "onze heures",
    "onze heures",
    "onze heures",
    "onze heures",
    "onze heures",
    "onze heures cinq",
    "onze heures cinq",
    "onze heures cinq",
    "onze heures cinq",
    "onze heures cinq",
    "onze heures dix",
    "onze heures dix",
    "onze heures dix",
    "onze heures dix",
    "onze heures dix",
    "onze heures et quart",
    "onze heures et quart",
    "onze heures et quart",
    "onze heures et quart",
    "onze heures et quart",
    "onze heures vingt",
    "onze heures vingt",
    "onze heures vingt",
    "onze heures vingt",
    "onze heures vingt",
    "onze heures vingt cinq",
    "onze heures vingt cinq",
    "onze heures vingt cinq",
    "onze heures vingt cinq",
    "onze heures vingt cinq",
    "onze heures et demie",
    "onze heures et demie",
    "onze heures et demie",
    "onze heures et demie",
    "onze heures et demie",
    "minuit moins vingt cinq",
    "minuit moins vingt cinq",
    "minuit moins vingt cinq",
    "minuit moins vingt cinq",
    "minuit moins vingt cinq",
    "minuit moins vingt",
    "minuit moins vingt",
    "minuit moins vingt",
    "minuit moins vingt",
    "minuit moins vingt",
    "minuit moins le quart",
    "minuit moins le quart",
    "minuit moins le quart",
    "minuit moins le quart",
    "minuit moins le quart",
    "minuit moins dix",
    "minuit moins dix",
    "minuit moins dix",
    "minuit moins dix",
    "minuit moins dix",
    "minuit moins cinq",
    "minuit moins cinq",
    "minuit moins cinq",
    "minuit moins cinq",
    "minuit moins cinq",
    " minuit"]:
   if len(s) >max:
       max= len(s)


print "max : %s " % max
